import random
import torch
from pathlib import Path
import yaml
import numpy as np
from src.operators.fno1d import FNO1d
from torch.optim import Adam
from data.dataset import load_numpy_data, split_tensors, create_dataloaders
import csv

# TODO: modify validate() to take any loss function instead of hard-coded val_rel_l2

# ------- LOAD CONFIG ----------

# Generated by codex 5.3
def load_config(config_path: str | None = None) -> dict:
    # train.py -> src/operators -> project root is parents[2]
    project_root = Path(__file__).resolve().parents[2]

    # default to root config file
    path = Path(config_path) if config_path else (project_root / "config.yaml")
    path = path.expanduser().resolve()

    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    if not isinstance(cfg, dict):
        raise ValueError(f"Config must be a mapping/dict, got: {type(cfg)}")

    return cfg

# --------- TRAINING -------------

def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    np.random.seed(seed)

def train_one_epoch(model, train_loader, optimizer, loss_fn) -> float:
    model.train()
    training_loss = 0.0

    for x_batch, y_batch in train_loader:
        optimizer.zero_grad()

        y_pred = model(x_batch)

        # keep everything (B, N, 1)
        loss = loss_fn(y_pred, y_batch)

        loss.backward()
        optimizer.step()

        training_loss += loss.item()

    training_loss /= len(train_loader)
    return training_loss


def validate(model, val_loader) -> float:
    """This function will output the val_rel_l2 loss after N epochs during training"""
    with torch.no_grad():
        model.eval()
        val_loss = 0.0

        for x_batch, y_batch in val_loader:
            y_pred = model(x_batch)

            val_rel_l2 = (torch.mean((y_pred - y_batch)**2)/torch.mean(y_batch**2)) ** 0.5 * 100

            val_loss += val_rel_l2.item()

        val_loss /= len(val_loader)

        return val_loss


def run(config: dict, seed: int, run_dir: str) -> dict[str, float | str]:
    set_seed(seed)

    # ------ RUN PATH -------
    run_path = Path(run_dir)
    run_path.mkdir(parents=True, exist_ok=True)

    # ------- LOGGING --------
    csv_path = run_path / "train_metrics.csv"
    csv_file = csv_path.open("w", newline="")
    csv_writer = csv.DictWriter(
        csv_file,
        fieldnames=["epoch", "train_loss", "val_rel_l2", "lr", "is_best"]
    )
    csv_writer.writeheader()

    # ------ DATA --------

    batch_size = config['training']['batch_size']
    x_data, y_data = load_numpy_data(config['data']['x_data_path'], config['data']['y_data_path'])
    n_train, n_val, n_test = config['data']['train_split'], config['data']['val_split'], config['data']['test_split']
    in_f_train, out_f_train, in_f_val, out_f_val, in_f_test, out_f_test = split_tensors(x_data=x_data, y_data=y_data,
                                                                                        n_train=n_train, n_val=n_val,
                                                                                        n_test=n_test)
    training_set, validation_set, test_set = create_dataloaders(in_f_train=in_f_train, out_f_train=out_f_train,
                                                                in_f_val=in_f_val, out_f_val=out_f_val,
                                                                in_f_test=in_f_test, out_f_test=out_f_test,
                                                                batch_size=batch_size)

    # -------- MODEL / HYPERPARAMS ---------

    fno = FNO1d(config['model']['parameters']['modes'], config['model']['parameters']['width'])

    optimizer = Adam(fno.parameters(), lr=config['training']['learning_rate'], weight_decay=config['training']['weight_decay'])
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer=optimizer, step_size=config['training']['scheduler']['step_size'], gamma=config['training']['scheduler']['gamma'])
    loss_fn = torch.nn.MSELoss()

    epochs = config['training']['epochs']
    validate_every = config['training']['validate_every']
    patience = config['training']['patience']

    # --------- TRAINING LAYER --------

    best_val_loss = float('inf')
    best_path = run_path / "fno1d_best.pt"
    bad_epochs = 0

    for epoch in range(epochs):
        train_loss = train_one_epoch(model=fno, train_loader=training_set, optimizer=optimizer, loss_fn = loss_fn)
        scheduler.step()

        print(f"Training loss for epoch {epoch} is {train_loss}")
        is_best = 0

        if (epoch % validate_every) == 0:
            val_loss = validate(model=fno, val_loader=validation_set)
            print(f"Validation loss for epoch {epoch} is {val_loss}")

            # save best
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                bad_epochs = 0
                is_best = 1

                torch.save(
                    {
                        "epoch": epoch,
                        "config": config,
                        "seed": seed,
                        "model_state": fno.state_dict(),
                        "optimizer_state": optimizer.state_dict(),
                        "scheduler_state": scheduler.state_dict(),
                        "best_val": best_val_loss
                    },
                    best_path
                )
                print(f"Saved new best: {best_val_loss} -> {best_path}")

            else:
                bad_epochs += 1
                if bad_epochs >= patience:
                    print(f"Early stopping: no improvement for {patience} evaluations.")
                    # log the last epoch row before breaking
                    pass

        # log every epoch (val_rel_l2 blank if not computed)
        lr = optimizer.param_groups[0]["lr"]
        csv_writer.writerow(
            {
                "epoch": epoch,
                "train_loss": float(train_loss),
                "val_rel_l2": "" if val_loss is None else float(val_loss),
                "lr": float(lr),
                "is_best": int(is_best)
            }
        )
        csv_file.flush()

        if (epoch % validate_every) == 0 and bad_epochs >= patience:
            break

    csv_file.close()
    return {"best_val": best_val_loss, "best_path": str(best_path)}


if __name__ == '__main__':
    config = load_config("/Users/henriklind/Desktop/no-tps-ihcp/config.yaml")
    base_run_dir = Path(config['training']['run']['run_dir'])

    # loop through all the seeds in the config
    for seed in config['training']['seeds']:
        seed_run_dir = base_run_dir / f"seed{seed}"
        run(config, seed, run_dir=str(seed_run_dir))
