# YAML file for data paths and hyperparameters

defaults:
  - paths: default
  - search_space: medium
  - override hydra/sweeper: optuna_local
  - _self_

config_id: 0

experiment:
  name: ${oc.env:EXPERIMENT_NAME,experiment0}

tuning:
  n_trials: 6
  direction: minimize
  objective: best_val_mean

model:
  type: 1D FNO
  parameters:
    modes: 16
    width: 64
    in_channels: 2
    out_channels: 1
    layers: 4
    activation: "Tanh"

training:
  batch_size: 10
  epochs: 1500
  learning_rate: 0.001
  weight_decay: 1.0e-5
  scheduler:
    step_size: 50
    gamma: 0.5
  optimizer: "Adam"
  loss_function: "MSELoss"
  validate_every: 10
  patience: 10
  checkpoint_metric: "val_rel_l2"
  seeds: [0, 1, 2]
  run:
    run_dir: ${paths.runs_root}/${experiment.name}/config${config_id}

evaluation:
  validation:
  test:

data:
  x_data_path: ${paths.data_dir}/x_data.npy
  y_data_path: ${paths.data_dir}/y_data.npy
  train_split: 362
  val_split: 78
  test_split: 78
  x_shape: "samples, N, (T0, x)"
  y_shape: "samples, N, T_final"

hydra:
  mode: MULTIRUN
  job:
    chdir: false
  run:
    dir: ${paths.runs_root}/${experiment.name}/single_run
  sweep:
    dir: ${paths.runs_root}/${experiment.name}/multirun
    subdir: ${hydra.job.num}
