# @package hydra.sweeper
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
study_name: ${experiment.name}
storage: sqlite:///${oc.env:RUNS_ROOT,${oc.env:PROJECT_ROOT}/runs}/${experiment.name}/optuna_study.db
n_trials: ${tuning.n_trials}
n_jobs: 1
direction: ${tuning.direction}
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42
params: ${search_space.params}
search_space: null
custom_search_space: null
